baseurl: '/LandingPage'
exclude: ['README.md']
permalink: pretty
title: 'GuideMe'

google_analytics_id: ""
logo:
  mobile: "images/favicon.ico"
  desktop: "images/favicon.ico"
  desktop_height: "36px"
footer:
  copyright_text: 'GuideMe © 2020'

seo:
  meta_og_title: "GuideMe - The lighthouse of learning."
  meta_og_image: images/landingpage_screenshot.png
  meta_og_type: "website"
  meta_og_description: GuideMe is the learning assistant that helps you keep your most important notes at hand, and brings content vetted by other learners closer.

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
