baseurl: '/LandingPage'
exclude: ['README.md']
permalink: pretty
title: 'GuideMe'

google_analytics_id: ""
logo:
  mobile: "images/favicon.ico"
  desktop: "images/favicon.ico"
  desktop_height: "36px"
footer:
  copyright_text: 'GuideMe © 2020'

seo:
  meta_og_title: "GuideMe - The lighthouse of learning."
  meta_og_image: images/landingpage_screenshot.png
  meta_og_type: "website"
  meta_og_description: "GuideMe is a learning assistant. It aids your learning journeys, recommending you the best path based on your level, while also helping you organize information. Let us guide you to a more knowledgeable self."

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
